# Generated by Django 4.0.3 on 2022-04-02 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcustommodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d9b91cb-3b33-41d3-ae0a-03a82fbea3a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
