# Generated by Django 4.0.3 on 2022-04-02 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_useraccountcustommodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcustommodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f011e50-1a4e-4370-b59f-b0eb3f141e49'), editable=False, primary_key=True, serialize=False),
        ),
    ]
