# Generated by Django 4.0.3 on 2022-04-02 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_useraccountcustommodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcustommodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdc30cca-5eeb-4c81-9e38-c745acf8eeac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
