# Generated by Django 4.0.3 on 2022-04-02 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_alter_useraccountcustommodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcustommodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d5c9edf-2185-4c4a-829b-78fec42f7042'), editable=False, primary_key=True, serialize=False),
        ),
    ]
