# Generated by Django 4.0.3 on 2022-04-02 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47325032-aa56-42e9-b337-00b7c9114518'), editable=False, primary_key=True, serialize=False),
        ),
    ]
