# Generated by Django 4.0.3 on 2022-04-02 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c97659de-a0e0-4898-9e23-15ef04397a66'), editable=False, primary_key=True, serialize=False),
        ),
    ]
