# Generated by Django 4.0.3 on 2022-04-02 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9133f23e-5899-4eaf-9bfb-64411fd90af1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
