# Generated by Django 4.0.3 on 2022-04-02 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30b44633-f131-45f2-a4a2-9935a37ef74a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
